{% set name = "ultralytics" %}
{% set version = "8.4.33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0f45846fea8cf70b8e332e31334b8c42eec35f649f57b9012fc81721f695339a

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py<38]
  entry_points:
    - yolo = ultralytics.cfg:entrypoint
    - ultralytics = ultralytics.cfg:entrypoint

requirements:
  host:
    - python
    - pip
    - setuptools >=70.0.0,<=82.0.1
    - wheel
  run:
    - python
    - numpy >=1.23
    - matplotlib-base >=3.3.0
    - opencv >=4.6.0
    - pillow >=7.1.2
    - pyyaml >=5.3.1
    - requests >=2.23.0
    - scipy >=1.4.1
    - pytorch >=1.8.0  # [unix]
    - pytorch >=1.8.0,!=2.4.0  # [win]
    - torchvision >=0.9.0 
    - psutil >=5.8.0
    - polars >=0.20.0
    - ultralytics-thop >=2.0.18
  run_constrained:
    # export
    # No numpy <2.0.0 for Python 3.13
    - numpy <2.0.0  # [py<313]
    - onnx >=1.12.0  # [not osx]
    - onnx >=1.12.0,<1.18.0  # [osx]
    - onnxslim >=0.1.82
    - coremltools >=9.0  # [not win and py<=313]
    - scikit-learn >=1.3.2  # [not win and py<=313]
    - openvino >=2024.0.0
    # Remove tensorflow upper bound to avoid solver failures between tensorflow/pytorch/torchvision
    - tensorflow >=2.0.0
    - tensorflowjs >=2.0.0
    - ydf <0.13.0  # [not aarch64]
    - tensorstore >=0.1.63  # [aarch64 and py>=39]
    - h5py !=3.11.0  # [aarch64]
    - packaging >=26.0 # [linux and aarch64 and py>=313]
    # solutions
    - shapely >=2.0.0
    - streamlit >=1.51.0  # [py>=310]
    - streamlit >=1.29.0,<1.51.0  # [py<310 and (not linux)]
    - flask >=3.0.1
    # extra
    - albumentations>=1.4.6
    - faster-coco-eval >=1.6.7

{% set deselect_tests = "" %}
# Failing only on CI, requires GUI/display (SIGABRT when no screen: "Cannot create window: no screens available").
{% set deselect_tests = deselect_tests + " --deselect=tests/test_python.py::test_utils_checks" %}  # [osx]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_solutions.py" %}  # [osx]
{% set deselect_tests = deselect_tests + " --deselect=tests/test_cli.py::test_solutions" %}  # [osx]

# [LINUX64 PY313]:
# E   AttributeError: module 'tensorflow._api.v2.compat.v2.__internal__' has no attribute 'register_load_context_function'. Did you mean: 'register_call_context_function'?
# Upstream tests are automatically installing tf_keras-2.15.0 which is not compatible with tensorflow-2.20.0. 
# https://github.com/keras-team/tf-keras/issues/257
# This issue can be fixed by pinning tf-keras to test environment but tf_keras<=2.19.0 is not available for Python 3.13 on the main channel
# Upstream requirement: https://github.com/ultralytics/ultralytics/blob/v8.4.19/ultralytics/engine/exporter.py#L1062
# [LINUX-AARCH64 ALL PYTHONS]:
# E ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found
{% set deselect_tests = deselect_tests + " --deselect=tests/test_exports.py::test_export_tflite" %}  # [(linux64 and py>=313) or aarch64]

# [LINUX-AARCH64 PY312/PY313]:
# openvivo is not available on main channel
# Upstream test env tries to install it during test execution using pip but openvivo is not available for linux-aarch64 py>=312
# This is why those tests are working on other platforms and pythons.
# Ultralytics requirement ['openvino>=2024.0.0'] not found, attempting AutoUpdate...
# WARNING requirements: Command 'pip install --no-cache-dir "openvino>=2024.0.0" ' returned non-zero exit status 1.
# ERROR: Could not find a version that satisfies the requirement openvino>=2024.0.0 (from versions: none)
# ERROR: No matching distribution found for openvino>=2024.0.0
{% set deselect_tests = deselect_tests + " --deselect=tests/test_exports.py::test_export_openvino" %}  # [aarch64 and py>=312]

test:
  source_files:
    - tests
  imports:
    - ultralytics
    - ultralytics.cfg
    - ultralytics.data
    - ultralytics.data.annotator
    - ultralytics.data.augment
    - ultralytics.data.build
    - ultralytics.data.converter
    - ultralytics.data.dataset
    - ultralytics.data.loaders
    - ultralytics.data.split
    - ultralytics.data.utils
    - ultralytics.engine.exporter
    - ultralytics.engine.model
    - ultralytics.engine.predictor
    - ultralytics.engine.results
    - ultralytics.engine.trainer
    - ultralytics.engine.validator
    - ultralytics.hub
    - ultralytics.hub.auth
    - ultralytics.hub.session
    - ultralytics.hub.utils
    - ultralytics.models
    - ultralytics.models.sam.modules.blocks
    - ultralytics.models.sam.modules.utils
    - ultralytics.models.yolo
    - ultralytics.models.yolo.classify.predict
    - ultralytics.models.yolo.classify.train
    - ultralytics.models.yolo.classify.val
    - ultralytics.models.yolo.detect
    - ultralytics.models.yolo.detect.predict
    - ultralytics.models.yolo.segment
    - ultralytics.models.yolo.world
    - ultralytics.models.yolo.world.train_world
    - ultralytics.nn.autobackend
    - ultralytics.nn.modules
    - ultralytics.nn.modules.head
    - ultralytics.nn.modules.transformer
    - ultralytics.nn.modules.utils
    - ultralytics.nn.tasks
    - ultralytics.optim
    - ultralytics.solutions.config
    - ultralytics.solutions.object_counter
    - ultralytics.solutions.solutions
    - ultralytics.utils
    - ultralytics.utils.autobatch
    - ultralytics.utils.autodevice
    - ultralytics.utils.checks
    - ultralytics.utils.cpu
    - ultralytics.utils.dist
    - ultralytics.utils.downloads
    - ultralytics.utils.errors
    - ultralytics.utils.events
    - ultralytics.utils.export
    - ultralytics.utils.files
    - ultralytics.utils.git
    - ultralytics.utils.instance
    - ultralytics.utils.loss
    - ultralytics.utils.metrics
    - ultralytics.utils.nms
    - ultralytics.utils.ops
    - ultralytics.utils.patches
    - ultralytics.utils.plotting
    - ultralytics.utils.tal
    - ultralytics.utils.torch_utils
    - ultralytics.utils.tqdm
  requires:
    - pip
    - pytest
    - git
    - tensorflow
    # https://github.com/AnacondaRecipes/torchvision-feedstock/blob/master/recipe/meta.yaml#L8
    - pytorch-cpu 2.7
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # Unit tests after positive run just hanging on results prompt on osx.
    - pytest -v tests {{ deselect_tests }} # [not (osx and py>=313)]
    - yolo checks
    - ultralytics version

about:
  home: https://ultralytics.com
  summary: Ultralytics YOLO for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.
  license: AGPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  description: |
    Ultralytics creates cutting-edge, state-of-the-art (SOTA) YOLO models built on years of
    foundational research in computer vision and AI. Constantly updated for performance and
    flexibility, our models are fast, accurate, and easy to use. They excel at object detection, tracking,
    instance segmentation, image classification, and pose estimation tasks.
  doc_url: https://docs.ultralytics.com
  dev_url: https://github.com/ultralytics/ultralytics

extra:
  recipe-maintainers:
    - onuralpszr
    - UltralyticsAssistant
    - glenn-jocher
    - Laughing-q
    - pderrenger